"use client";

import { useEffect, useState } from "react";
import { Download } from "lucide-react";
import { PageHeader, Card, EmptyState } from "@/components/ui";

// Renders the newest ~/.vibelog/digests/*.md. The digest format is our own
// (headings, tables, numbered lines), so a tiny renderer beats a markdown dep.

function renderMd(md: string) {
  const out: React.ReactNode[] = [];
  let table: string[][] = [];
  let key = 0;
  const flushTable = () => {
    if (!table.length) return;
    const [head, ...rows] = table;
    out.push(
      <table key={key++} className="my-4 w-full text-sm">
        <thead>
          <tr className="border-b border-line font-mono text-[10px] uppercase tracking-wider text-ink-3">
            {head.map((h, i) => (
              <th key={i} className={`py-2 font-normal ${i === 0 ? "text-left" : "text-right"}`}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i} className="border-b border-line last:border-0">
              {r.map((c, j) => (
                <td
                  key={j}
                  className={`py-2 text-xs ${
                    j === 0 ? "text-left font-mono" : "text-right font-mono tabular-nums text-ink-2"
                  }`}
                >
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    );
    table = [];
  };
  for (const line of md.split("\n")) {
    if (line.startsWith("|")) {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim());
      if (!cells.every((c) => /^-+$/.test(c))) table.push(cells);
      continue;
    }
    flushTable();
    if (line.startsWith("## "))
      out.push(
        <h2
          key={key++}
          className="mt-8 mb-2 font-mono text-[11px] uppercase tracking-wider text-ink-3"
        >
          {line.slice(3)}
        </h2>
      );
    else if (line.startsWith("# "))
      out.push(
        <h1 key={key++} className="font-serif text-3xl tracking-tight">
          {line.slice(2)}
        </h1>
      );
    else if (line.trim())
      out.push(
        <p key={key++} className="text-sm leading-relaxed text-ink">
          {line}
        </p>
      );
  }
  flushTable();
  return out;
}

export function DigestClient() {
  const [digest, setDigest] = useState<{ name: string; markdown: string } | null | undefined>();

  useEffect(() => {
    let on = true;
    fetch("/api/digest")
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => on && setDigest(d))
      .catch(() => on && setDigest(null));
    return () => {
      on = false;
    };
  }, []);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Weekly digest"
        sub="A markdown report of last week, generated by the collector every Monday morning"
        right={
          digest ? (
            <a
              href="/api/digest?raw=1"
              className="inline-flex items-center gap-1.5 rounded-md border border-line px-3 py-1.5 text-xs font-medium transition-colors hover:border-line-2 hover:bg-wash"
            >
              <Download size={13} />
              {digest.name}
            </a>
          ) : undefined
        }
      />
      {digest === undefined ? null : digest === null ? (
        <EmptyState
          title="No digest yet."
          sub="Your first digest lands Monday morning, once a week of sessions exists. Keep vibelog start running and it happens on its own."
          code="vibelog start"
        />
      ) : (
        <Card className="px-8 py-6">{renderMd(digest.markdown)}</Card>
      )}
    </div>
  );
}
